### PR TITLE
Handle AsciiDoc better, reuse HTML pipeline filters (fixes #9263)

### LINKED ISSUE #9263: Relative links doesn’t work in AsciiDoc files
When I use a relative link inside an `.adoc` file, e.g. `link:LICENSE` in `README.adoc`, then the rendered link is incorrect, `/{username}/LICENSE` instead of `/{username}/{project-name}/blob/master/LICENSE`.

This bothers the most in the case of images. My colleagues currently works on some technical reports and they’re displaying these primarily on GitLab and they are not much happy for not seeing their graphs etc.

### PR DESCRIPTION
**Pull request by jirutka**
This PR basically makes AsciiDoc a “first-class citizen” in GitLab, so we can reuse some HTML pipeline filters etc. The main reason why I’ve done this is to use RelativeLinkFilter (implemented in #9276) for AsciiDoc, and so fix #9263.

Since we don’t need `github-markup` for AsciiDoc anymore, I’ve updated the Asciidoctor gem to the latest version. The current used version (0.1.4) is ancient.

/cc @tsigo @randx @mojavelinux

### CODE REVIEW

File: lib/gitlab/asciidoc.rb [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+  # Parser/renderer for the AsciiDoc format that uses Asciidoctor and filters
+  # the resulting HTML through HTML pipeline filters.
+  module Asciidoc
+
+    # Provide autoload paths for filters to prevent a circular dependency error
+    autoload :RelativeLinkFilter, 'gitlab/markdown/relative_link_filter'
+
+    DEFAULT_ADOC_ATTRS = [
+      'showtitle', 'idprefix=user-content-', 'idseparator=-', 'env=github',
+      'env-github', 'env=gitlab', 'env-gitlab',
```
Comment (mojavelinux) [inline lib/gitlab/asciidoc.rb]: The `env=github` and `env-github` attributes should be removed. We should only use `env=gitlab` and `env-gitlab` attributes.

File: lib/gitlab/asciidoc.rb [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+        attributes: []
+      )
+      asciidoc_opts[:attributes].unshift(*DEFAULT_ADOC_ATTRS)
+
+      html = ::Asciidoctor.convert(input, asciidoc_opts)
+
+      if context[:project]
+        result = HTML::Pipeline.new(filters).call(html, context)
+
+        save_opts = html_opts[:xhtml] ?
```
Comment (mojavelinux) [inline lib/gitlab/asciidoc.rb]: If `html_opts[:xhtml]` is specified, then I think the Asciidoctor `:backend` should be set to `:xhtml5`.

File: lib/gitlab/markdown_helper.rb [hunk 3]
```diff
@@ -22,6 +22,15 @@ def gitlab_markdown?(filename)
       filename.downcase.end_with?(*%w(.mdown .md .markdown))
     end
 
+    # Public: Determines if the given filename has AsciiDoc extension.
+    #
+    # filename - Filename string to check
+    #
+    # Returns boolean
+    def asciidoc?(filename)
+      filename.downcase.end_with?(*%w(.adoc .asc .asciidoc))
```
Comment (mojavelinux) [inline lib/gitlab/markdown_helper.rb]: I think `.asc` should be removed. It should either be `.adoc .asciidoc` or `.adoc .ad .asciidoc`.

**Comment by mojavelinux** [comment]
Overall it looks good to me! I didn't run it, but I reviewed the code.

**Comment by mojavelinux** [comment]
> The current used version (0.1.4) is ancient.

+1000 Let's get out in front of GitHub!

**Comment by jirutka** [comment]
@mojavelinux I’ve implemented your suggestions and updated the PR. Thanks!

File: lib/gitlab/asciidoc.rb (hunk 2 above)
Comment (jirutka) [inline lib/gitlab/asciidoc.rb]: Done.

**Comment by randx** [comment]
@tsigo can you take a look and merge if ok?

**Comment by Razer6** [comment]
@randx Can you add him as a collaborator to the GitHub repo? He does not have rights right now.

**Comment by randx** [comment]
@Razer6 thank you. I invited him

**Comment by mojavelinux** [comment]
@jirutka Nice work!

**Comment by randx** [comment]
@tsigo can you take a look and merge if ok?

File: CHANGELOG [hunk 4]
```diff
@@ -67,6 +67,8 @@ v 7.11.0 (unreleased)
   - Spin spinner icon next to "Checking for CI status..." on MR page.
   - Fix reference links in dashboard activity and ATOM feeds.
   - Ensure that the first added admin performs repository imports
+  - Update Asciidoctor gem to version 1.5.2. (Jakub Jirutka)
```
Comment (tsigo) [inline CHANGELOG]: I don't think this needs a changelog entry.

Comment (jirutka) [inline CHANGELOG]: Why do you think so? It’s an important change for users that uses AsciiDoc in GitLab.

File: lib/gitlab/asciidoc.rb [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+    #                 :commit
+    #                 :project
+    #                 :project_wiki
+    #                 :requested_path
+    #                 :ref
+    # asciidoc_opts - a Hash of options to pass to the Asciidoctor converter
+    # html_opts     - a Hash of options for HTML output:
+    #                 :xhtml - output XHTML instead of HTML
+    #
+    def self.render_asciidoc(input, context, asciidoc_opts = {}, html_opts = {})
```
Comment (tsigo) [inline lib/gitlab/asciidoc.rb]: Does this need to be called `render_asciidoc`? We're in the Asciidoc class already, I think `render` would be better.

Comment (jirutka) [inline lib/gitlab/asciidoc.rb]: Nope, we can rename it to `render`. btw We’re actually in a module, not a class.

**Comment by tsigo** [comment]
Will merge after `render` rename and CI pass.

**Comment by mojavelinux** [comment]
:+1:

**Comment by jirutka** [comment]
@tsigo Method `render_asciidoc` renamed to `render`, commits rebased to the current master and CI passed. Let’s merge it! :smile_cat:
